---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
#  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[gunicorn_test::default]
      - recipe[gunicorn_test::lwrps]
      - recipe[minitest-handler]
#    attributes:
#      python:
#        install_method: source
#  - name: lwrps
#    run_list:
#      - recipe[gunicorn_test::lwrps]
#    attributes:
