language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

before_install:
  - "echo 'gem: --no-ri --no-doc' > ~/.gemrc"

script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
  - bundle exec rspec --color --format progress