name 'gunicorn_test'
maintainer 'Jono Wells'
maintainer_email '7@oj.io'
license 'Apache 2.0'
description 'This cookbook is used with test-kitchen to test the parent, gunicorn cookbook'
version '1.0.0'
